import 'package:flutter_test/flutter_test.dart';
import 'package:sixpos/presentation/navigation/modulo_central_pdv.dart';
import 'package:sixpos/presentation/navigation/web_navigation_destination_mapper.dart';
import 'package:sixpos/presentation/navigation/web_navigation_item.dart';

void main() {
  group('webNavigationDestinationForModuloCentralPdv', () {
    test('mapeia modulos centrais para destinos ativos da navegacao Web', () {
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.seletor),
        WebNavigationDestination.home,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.cockpit),
        WebNavigationDestination.home,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.vendas),
        WebNavigationDestination.operationsPointOfSale,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.recebimento,
        ),
        WebNavigationDestination.operationsPointOfSale,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.orcamento),
        WebNavigationDestination.operationsPointOfSale,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.atendimentoTecnico,
        ),
        WebNavigationDestination.operationsTechnicalServices,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.ordemServico,
        ),
        WebNavigationDestination.operationsTechnicalServices,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.compras),
        WebNavigationDestination.operationsPurchases,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.produtos),
        WebNavigationDestination.catalogProducts,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.servicos),
        WebNavigationDestination.catalogServices,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(ModuloCentralPDV.estoque),
        WebNavigationDestination.catalogStock,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.categorias,
        ),
        WebNavigationDestination.catalogCategories,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.clientesList,
        ),
        WebNavigationDestination.peopleCustomers,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.colaboradoresList,
        ),
        WebNavigationDestination.peopleCollaborators,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.desempenho,
        ),
        WebNavigationDestination.peoplePerformance,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.operacoesCaixa,
        ),
        WebNavigationDestination.cash,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.agendaFinanceira,
        ),
        WebNavigationDestination.financialAgenda,
      );
      expect(
        webNavigationDestinationForModuloCentralPdv(
          ModuloCentralPDV.configuracoes,
        ),
        WebNavigationDestination.settings,
      );
    });
  });
}
