name: sixpos
description: "Six Point of Sale"
publish_to: 'none'
version: 1.132.0+133
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.63.0
  stomp_dart_client: ^0.4.4
  flutter_local_notifications: ^17.0.0
  signature: ^5.3.0
  flutter_animate: ^4.2.0
  http_interceptor: ^3.0.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  share_plus: ^10.1.4
  mobile_scanner: ^7.0.1
  syncfusion_flutter_gauges: any
  lottie: ^1.4.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/processando_backend.json
    - assets/animations/product_boxes_loading.json
    - "assets/animations/splash screen/1.webp"
    - "assets/animations/splash screen/2.webp"
    - "assets/animations/splash screen/3.webp"
    - "assets/animations/splash screen/4.webp"
    - "assets/animations/splash screen/5.webp"
    - "assets/animations/tela login/1.webp"
    - "assets/animations/tela login/2.webp"
    - "assets/animations/tela login/3.webp"
    - "assets/animations/tela login/4.webp"
    - "assets/animations/tela login/5.webp"
    - "assets/animations/tela login/6.webp"
    - "assets/animations/tela login/7.webp"
    - "assets/animations/tela login/8.webp"
    - "assets/animations/tela login/9.webp"
    - "assets/animations/tela login/10.webp"
    - assets/images/placeholder.png
    - assets/images/six-logo-flecha.webp
    - "assets/images/atendimento mobile/atendimento-hero.webp"
    - "assets/images/atendimento mobile/acao-nova-venda.png"
    - "assets/images/atendimento mobile/acao-novo-servico.png"
    - "assets/images/atendimento mobile/acao-receber.png"
    - "assets/images/atendimento mobile/acao-operacoes-caixa.png"
    - "assets/images/atendimento mobile/acao-devolucoes.png"
    - "assets/images/atendimento mobile/acao-nova-venda.webp"
    - "assets/images/atendimento mobile/acao-novo-servico.webp"
    - "assets/images/atendimento mobile/acao-receber.webp"
    - "assets/images/vendas mobile/vendas.webp"
    - "assets/images/vendas mobile/recebimento.webp"
    - "assets/images/vendas mobile/consultar.webp"
    - "assets/images/servicos mobile/servico.webp"
    - "assets/images/servicos mobile/consultar.webp"
    - assets/images/onboading/1-bem-vindo.webp
    - assets/images/onboading/2-cadastro-rapido.webp
    - assets/images/onboading/3-gestao-tecnica.webp
    - assets/images/onboading/4-controle-financeiro.webp
    - assets/images/unsplash-1.webp
