name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Instalar dependências
        run: flutter pub get

#      - name: Build Android APK
#        run: flutter build apk --release

#      - name: Build iOS (apenas macOS)
#        if: runner.os == 'macOS'
#        run: flutter build ios --release

#  deploy-android:
#    needs: build-flutter
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.19.3'
#
#      - name: Build App Bundle
#        run: flutter build appbundle
#
#      - name: Deploy para Google Play
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
#          packageName: com.seu.pacote
#          releaseFiles: build/app/outputs/bundle/release/app-release.aab
#          track: internal  # ou beta, production...

#  deploy-ios:
#    needs: build-flutter
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.19.3'
#
#      - name: Instalar dependências
#        run: flutter pub get
#
#      - name: Build iOS
#        run: flutter build ios --release
#
#      - name: Deploy com Fastlane
#        uses: maierj/fastlane-action@v3
#        with:
#          lane: ios beta
#          subdirectory: ./ios
#        env:
#          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
